import express from "express";
import pg from "pg";
import crypto from "node:crypto";
import io from "socket.io-client";

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT || 3000);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized:false } : false });
const cfg = { admin:process.env.ADMIN_SECRET||"", obs:process.env.OBS_SECRET||"", session:process.env.SESSION_SECRET||"", clientId:process.env.CHZZK_CLIENT_ID||"", clientSecret:process.env.CHZZK_CLIENT_SECRET||"", publicUrl:(process.env.PUBLIC_URL||"").replace(/\/$/,"") };
let socket = null, chzzkStatus = "연결 안 됨", oauthStates = new Map();

app.use(express.json({limit:"32kb"})); app.use(express.static("public"));
const deny = res => res.status(401).json({error:"비밀키가 올바르지 않습니다."});
const isAdmin = req => Boolean(cfg.admin) && (req.get("x-admin-key") === cfg.admin || req.query.key === cfg.admin);
const canRead = req => isAdmin(req) || (Boolean(cfg.obs) && req.query.key === cfg.obs);

async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS queue_items(id BIGSERIAL PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN('song','join')),requester TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'waiting' CHECK(status IN('waiting','called','done')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`); await restoreChzzk();}
async function setting(key){const r=await pool.query("SELECT value FROM settings WHERE key=$1",[key]);return r.rows[0]?.value}
async function setSetting(key,value){await pool.query("INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[key,value])}

function crypt(text,encrypt=true){if(!cfg.session)throw new Error("SESSION_SECRET 미설정");const key=crypto.createHash("sha256").update(cfg.session).digest();if(encrypt){const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key,iv),body=Buffer.concat([c.update(text,"utf8"),c.final()]);return [iv.toString("base64"),c.getAuthTag().toString("base64"),body.toString("base64")].join(".")}const[iv,tag,body]=text.split(".").map(v=>Buffer.from(v,"base64")),d=crypto.createDecipheriv("aes-256-gcm",key,iv);d.setAuthTag(tag);return Buffer.concat([d.update(body),d.final()]).toString("utf8")}
async function addChat(requester,message){const user=String(requester||"").trim().slice(0,40),chat=String(message||"").trim();const kind=chat==="!시참"?"join":chat.startsWith("!노래 ")?"song":null;if(!kind)return {ignored:true,message:"신청 명령어가 아닙니다."};const title=kind==="song"?chat.slice(4).trim().slice(0,100):"";if(!user||kind==="song"&&!title)throw new Error("닉네임 또는 곡명이 없습니다.");const open=await setting(kind==="song"?"acceptingSongs":"acceptingJoin");if(open==="false")throw new Error(`${kind==="song"?"노래":"시참"} 신청이 마감되었습니다.`);const dup=kind==="join"?await pool.query("SELECT id FROM queue_items WHERE kind='join' AND requester=$1 AND status<>'done' LIMIT 1",[user]):await pool.query("SELECT id FROM queue_items WHERE kind='song' AND lower(title)=lower($1) AND status<>'done' LIMIT 1",[title]);if(dup.rowCount)throw new Error("이미 대기열에 있는 신청입니다.");const r=await pool.query("INSERT INTO queue_items(kind,requester,title) VALUES($1,$2,$3) RETURNING *",[kind,user,title]);return {item:r.rows[0],message:kind==="song"?`“${title}” 신청 완료`:`${user}님 시참 신청 완료`}}

app.get("/health",(_,res)=>res.json({ok:true,chzzkStatus}));
app.get("/api/queue",async(req,res)=>{if(!canRead(req))return deny(res);const [items,a,b]=await Promise.all([pool.query("SELECT id,kind,requester,title,status,created_at AS \"createdAt\" FROM queue_items ORDER BY CASE WHEN status='called' THEN 0 ELSE 1 END,created_at"),setting("acceptingSongs"),setting("acceptingJoin")]);res.json({items:items.rows,acceptingSongs:a!=="false",acceptingJoin:b!=="false",chzzkStatus})});
app.post("/api/chat",async(req,res)=>{if(!isAdmin(req))return deny(res);try{res.status(201).json(await addChat(req.body.requester,req.body.message))}catch(e){res.status(409).json({error:e.message})}});
app.patch("/api/settings",async(req,res)=>{if(!isAdmin(req))return deny(res);if(!["acceptingSongs","acceptingJoin"].includes(req.body.key))return res.status(400).json({error:"잘못된 설정"});await setSetting(req.body.key,String(Boolean(req.body.value)));res.json({ok:true})});
app.patch("/api/queue/:id",async(req,res)=>{if(!isAdmin(req))return deny(res);const action=req.body.action,status=action==="call"?"called":action==="done"?"done":action==="restore"?"waiting":null;if(!status)return res.status(400).json({error:"잘못된 작업"});if(action==="call"){const t=await pool.query("SELECT kind FROM queue_items WHERE id=$1",[req.params.id]);if(!t.rowCount)return res.status(404).json({error:"신청 없음"});await pool.query("UPDATE queue_items SET status='waiting' WHERE kind=$1 AND status='called'",[t.rows[0].kind])}await pool.query("UPDATE queue_items SET status=$1 WHERE id=$2",[status,req.params.id]);res.json({ok:true})});
app.delete("/api/queue/:id",async(req,res)=>{if(!isAdmin(req))return deny(res);await pool.query("DELETE FROM queue_items WHERE id=$1",[req.params.id]);res.json({ok:true})});

app.get("/api/chzzk/login",(req,res)=>{if(!isAdmin(req))return deny(res);if(!cfg.clientId||!cfg.clientSecret||!cfg.publicUrl)return res.status(400).send("치지직 환경변수가 설정되지 않았습니다.");const state=crypto.randomBytes(24).toString("hex");oauthStates.set(state,Date.now()+600000);const redirectUri=`${cfg.publicUrl}/api/chzzk/callback`;res.redirect(`https://chzzk.naver.com/account-interlock?clientId=${encodeURIComponent(cfg.clientId)}&redirectUri=${encodeURIComponent(redirectUri)}&state=${state}`)});
app.get("/api/chzzk/callback",async(req,res)=>{try{const expiry=oauthStates.get(req.query.state);if(!expiry||expiry<Date.now())throw new Error("인증 요청이 만료되었습니다.");oauthStates.delete(req.query.state);const token=await chzzkFetch("/auth/v1/token",{method:"POST",body:JSON.stringify({grantType:"authorization_code",clientId:cfg.clientId,clientSecret:cfg.clientSecret,code:req.query.code,state:req.query.state})},false);await saveTokens(token);await connectChzzk(token.accessToken);res.redirect("/?connected=1")}catch(e){res.status(500).send(`치지직 연결 실패: ${e.message}`)}});
async function chzzkFetch(path,options={},bearer){const headers={"Content-Type":"application/json",...(bearer?{Authorization:`Bearer ${bearer}`}:{"Client-Id":cfg.clientId,"Client-Secret":cfg.clientSecret}),...(options.headers||{})};const r=await fetch(`https://openapi.chzzk.naver.com${path}`,{...options,headers});const j=await r.json().catch(()=>({}));if(!r.ok||j.code&&j.code!==200)throw new Error(j.message||`치지직 API ${r.status}`);return j.content||j}
async function saveTokens(t){await setSetting("chzzkTokens",crypt(JSON.stringify({accessToken:t.accessToken,refreshToken:t.refreshToken,expiresAt:Date.now()+Number(t.expiresIn||86400)*1000})))}
async function validToken(){const raw=await setting("chzzkTokens");if(!raw)return null;let t=JSON.parse(crypt(raw,false));if(t.expiresAt>Date.now()+60000)return t.accessToken;const n=await chzzkFetch("/auth/v1/token",{method:"POST",body:JSON.stringify({grantType:"refresh_token",refreshToken:t.refreshToken,clientId:cfg.clientId,clientSecret:cfg.clientSecret})},false);await saveTokens(n);return n.accessToken}
async function restoreChzzk(){try{const token=await validToken();if(token)await connectChzzk(token)}catch(e){chzzkStatus=`재연결 필요: ${e.message}`}}
async function connectChzzk(accessToken){if(socket)socket.disconnect();chzzkStatus="연결 중";const session=await chzzkFetch("/open/v1/sessions/auth",{method:"GET"},accessToken);socket=io.connect(session.url,{reconnection:true,forceNew:true,timeout:5000,transports:["websocket"]});socket.on("SYSTEM",async raw=>{try{const msg=typeof raw==="string"?JSON.parse(raw):raw;if(msg.type==="connected"){await chzzkFetch(`/open/v1/sessions/events/subscribe/chat?sessionKey=${encodeURIComponent(msg.data.sessionKey)}`,{method:"POST"},accessToken)}if(msg.type==="subscribed"&&msg.data.eventType==="CHAT")chzzkStatus="실시간 채팅 연결됨"}catch(e){chzzkStatus=`구독 오류: ${e.message}`}});socket.on("CHAT",async raw=>{try{const m=typeof raw==="string"?JSON.parse(raw):raw;await addChat(m.profile?.nickname||"치지직 시청자",m.content)}catch(e){if(!String(e.message).includes("신청 명령어"))console.warn(e.message)}});socket.on("disconnect",()=>{chzzkStatus="연결 끊김"});socket.on("error",e=>{chzzkStatus=`소켓 오류: ${e.message||e}`})}

init().then(()=>app.listen(port,"0.0.0.0",()=>console.log(`QUEUE ON :${port}`))).catch(e=>{console.error(e);process.exit(1)});
